name: Build

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday
    workflow_dispatch: ~

jobs:
    tests:
        runs-on: ubuntu-latest

        name: "PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}"

        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4, 8.0]
                symfony: [^3.4, ^4.4, ^5.2]

        env:
            APP_ENV: test

        steps:
            -
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    extensions: intl
                    tools: symfony
                    coverage: none

            -
                name: Get Composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -
                name: Cache Composer
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php }}-composer-

            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^1.10"
                    composer config extra.symfony.require "${{ matrix.symfony }}"

            -
                name: Temporary require ivory/google-map from ekyna fork
                if: matrix.symfony == '^5.2'
                run: |
                    composer config repositories.igm vcs https://github.com/ekyna/ivory-google-map
                    composer require --no-update --no-progress --no-scripts --no-plugins "ivory/google-map:dev-sf5"

            -
                name: Install PHP dependencies
                run: composer install --no-interaction --prefer-source

            -
                name: Run analysis
                run: composer validate --strict

            -
                name: Run PHPUnit
                run: vendor/bin/phpunit --configuration phpunit.ci.xml --coverage-clover clover.xml

            -
                name: Send coverage report
                if: github.repository == 'bresam/ivory-google-map-bundle'
                run: |
                    wget https://scrutinizer-ci.com/ocular.phar
                    php ocular.phar code-coverage:upload --format=php-clover clover.xml
